const quizData=[
  ['Как начинается формула в Excel?',['С символа =','С символа #','Со слова ФОРМУЛА'],0],
  ['Какую ссылку нужно закрепить при копировании формулы?',['A1',' $A$1 ','A:A'],1],
  ['Что вернёт функция СУММ?',['Среднее значение','Сумму чисел','Количество ячеек'],1],
  ['Ошибка #Н/Д обычно означает…',['Данные не найдены','Деление на ноль','Неверный тип данных'],0],
  ['Для поиска значения в таблице лучше использовать…',['ВПР / XLOOKUP','СЖПРОБЕЛЫ','СЛУЧМЕЖДУ'],0]
];
let step=0,score=0,chosen=null;
const show=(id)=>{document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));window.scrollTo(0,0)};
document.querySelectorAll('[data-goto]').forEach(x=>x.onclick=()=>show(x.dataset.goto));document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>show(x.dataset.view));
function renderQuiz(){let q=quizData[step];document.getElementById('step').textContent=`Вопрос ${step+1} из ${quizData.length}`;document.getElementById('quizBar').style.width=`${(step+1)*20}%`;document.getElementById('question').textContent=q[0];document.getElementById('answers').innerHTML=q[1].map((a,i)=>`<button type="button" class="answer" data-i="${i}">${a}</button>`).join('');document.getElementById('next').disabled=true;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');chosen=+b.dataset.i;document.getElementById('next').disabled=false});}
document.getElementById('next').onclick=()=>{if(chosen===quizData[step][2])score++;step++;if(step<quizData.length){renderQuiz();return}let pct=Math.round(score/quizData.length*100);let level=pct<=30?'Junior':pct<=60?'Middle':pct<=85?'Advanced':'Pro';document.getElementById('levelText').textContent=level;document.getElementById('levelTag').textContent=level;document.querySelector('.test-layout').innerHTML=`<div class="test-copy"><p class="eyebrow">Диагностика завершена</p><h1>Ваш уровень — ${level}</h1><p class="lead">Результат: <b>${pct}%</b>. Мы сформировали персональный маршрут, соответствующий вашему текущему уровню.</p><button class="primary" onclick="location.hash='';show('home')">Перейти к урокам</button></div><div class="quiz"><p class="eyebrow">Ваш следующий шаг</p><h2>Начните с урока «Формулы: логика и ссылки»</h2><p class="lead">Короткое видео, тренажёр и помощь ИИ-куратора уже доступны.</p></div>`};renderQuiz();
document.getElementById('file').onchange=e=>{let f=e.target.files[0];document.getElementById('uploadResult').textContent=f?`Файл «${f.name}» отправлен на проверку`:''};
document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();let input=document.getElementById('message'),text=input.value.trim();if(!text)return;let chat=document.getElementById('chat');chat.insertAdjacentHTML('beforeend',`<div class="student">${text}</div>`);let lower=text.toLowerCase();let reply=lower.includes('н/д')?'Ошибка #Н/Д означает, что совпадение не найдено. Проверьте: есть ли искомое значение в таблице и одинаковый ли формат данных. Что показывает формула, если проверить значение вручную?':lower.includes('сумм')?'Подсказка: функция СУММ складывает диапазон. Попробуйте сначала выделить ячейки с числами и посмотрите, какой диапазон Excel подставит автоматически.':'Давайте разберёмся. Покажите формулу или опишите, какой результат вы ожидаете — я задам наводящий вопрос.';setTimeout(()=>{chat.insertAdjacentHTML('beforeend',`<div class="bot">${reply}</div>`);chat.scrollTop=chat.scrollHeight},350);input.value=''};
document.getElementById('export').onclick=()=>{let csv='Сотрудник,Отдел,Уровень,Прогресс,Статус\nАнна Сергеева,Продажи,Middle,78%,В процессе\nДенис Белов,Финансы,Advanced,100%,Завершил\nМария Ким,Маркетинг,Junior,14%,Нужен контакт';let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='excel-academy-report.csv';a.click()};
